CREATE TABLE FOOD(
   FOOD TEXT PRIMARY KEY NOT NULL,
   MILK INT NOT NULL,
   EGGS INT NOT NULL,
   FISH INT NOT NULL,
   SHELLFISH INT NOT NULL,
   TREENUTS INT NOT NULL,
   PEANUTS INT NOT NULL,
   WHEAT INT NOT NULL,
   SOYBEAN INT NOT NULL,
   SESAME INT NOT NULL
);
INSERT INTO FOOD (FOOD, MILK, EGGS, FISH, SHELLFISH, TREENUTS, PEANUTS, WHEAT, SOYBEAN, SESAME)
VALUES ('snickers', 0, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO FOOD (FOOD, MILK, EGGS, FISH, SHELLFISH, TREENUTS, PEANUTS, WHEAT, SOYBEAN, SESAME)
VALUES ('doritos', 0, 0, 0, 0, 0, 0, 0, 0, 0);
